### ISSUE TITLE
Virtualbox Guest Addition seems not installed.

### ISSUE THREAD

**Issue by fy0** [kraksoft/vagrant-box-ubuntu#3]
LOG:

> Failed to mount folders in Linux guest. This is usually because
> the "vboxsf" file system is not available. Please verify that
> the guest additions are properly installed in the guest and
> can work properly. The command attempted was:
> 
> mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
> mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant
> 
> The error output from the last command was:
> 
> stdin: is not a tty
> mount: unknown filesystem type 'vboxsf'

**Comment by megane42** [comment]
``` bash
$ vagrant plugin install vagrant-vbguest
$ vagrant up
# same error occurs just once
$ vagrant reload
```

works for me.

**Comment by xzs1994** [comment]
> ```shell
> $ vagrant plugin install vagrant-vbguest
> $ vagrant up
> # same error occurs just once
> $ vagrant reload
> ```
> 
> works for me.

i think it's true because i used this command and it's usefully
